repos:
# python -m pre_commit install --hook-type pre-commit --hook-type pre-push --hook-type commit-msg
  # 添加清空日志文件的钩子
- repo: local
  hooks:
    - id: clear-log
      name: Clear Pre-Commit Log
      entry: >-
        bash -c 'truncate -s 0 assist/logs/pre-commit.log'
      language: system
      stages: [pre-commit]
      verbose: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files  # 禁止提交大文件
      args: [--maxkb=3072]
      log_file: assist/logs/pre-commit.log
    # - id: trailing-whitespace      # 检查行尾空格
    #   args: [ --markdown-linebreak-ext=md ]
    #   exclude: '\.js$'
    - id: check-json
      log_file: assist/logs/pre-commit.log
    - id: check-xml
      log_file: assist/logs/pre-commit.log
    - id: check-yaml
      log_file: assist/logs/pre-commit.log
    # - id: end-of-file-fixer
    #   exclude: '\.json$|\.lock$|\.js$'
    #   log_file: assist/logs/pre-commit.log
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.35.0
  hooks:
    - id: markdownlint             # Markdown 检查
      # exclude: '^docs/(README|CHANGELOG)\.md$'
      # args: ['--rules', 'MD013,MD041']
      args: ['--config', 'data\.markdownlint.yaml']
      # additional_dependencies: ['@markdownlint/cli@latest']
      log_file: assist/logs/pre-commit.log
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.22.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']
        log_file: assist/logs/pre-commit.log
- repo: local
  hooks:
    - id: hugo-build
      stages: [pre-push]
      name: Hugo Build Check
      entry: hugo build --gc --minify    # 自定义 Hugo 检查
      language: system
      files: '' # 无条件运行构建检查
      pass_filenames: false # 不传递文件名给 Hugo
      verbose: true
      log_file: assist/logs/pre-commit.log
